# Generated by Django 4.2 on 2024-11-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='score',
            field=models.IntegerField(),
        ),
    ]
