# Generated by Django 4.2 on 2024-10-21 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='descrption',
            new_name='description',
        ),
    ]
